name: shellcheck action workflow
on:
  push:
    branches: 
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  semantic_tag:
    runs-on: ubuntu-latest
    name: Semantic Tag
    steps:
      - name: step to generate semantic version
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main
          dry_run: false
          create_annotated_tag: true
      - name: step to print next semantic version
        id: tag_id
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          new_version=${{ steps.tag_version.outputs.new_version }}
          new_tag=${{ steps.tag_version.outputs.new_tag }}
          echo "new_tag=${new_tag}" >> "$GITHUB_OUTPUT"
          echo "new_version=${new_version}" >> "$GITHUB_OUTPUT"
    outputs:
      new_tag: ${{ steps.tag_id.outputs.new_tag }}
      new_version: ${{ steps.tag_id.outputs.new_version }}
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: semantic_tag
    steps:
      - name: step to create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.semantic_tag.outputs.new_tag }}
          release_name: Release ${{ needs.semantic_tag.outputs.new_tag }}
          body: |
            Changes in this Release
            - Added code to perform shell scripting linting
          draft: false
          prerelease: false
